### ISSUE TITLE
Remove bullet points from social media icons on the footer

### ISSUE THREAD

**Issue by lpatmo** [pybay/pybay_old#153]
Noticed some extra bullets near the social media icons on the footer of the site: 

![screen shot 2017-07-07 at 12 47 44 am](https://user-images.githubusercontent.com/4512699/27948285-2c8eb18a-62ae-11e7-88b9-4d2bd8a3f970.jpg)

Needs a `list-style: none`. 

Let me know if we should do this, and I can submit a PR.

**Comment by epsy** [comment]
Please do!
