### ISSUE TITLE
Might need to update requirements.txt

### ISSUE THREAD

**Issue by ccsv** [pybay/pybay_old#208]
I am getting this error when I ran navigate to pages on the latest pybay version. I am guessing the requirements.txt is not up to date 

Request Method: | GET
-- | --
http://localhost:8000/
1.9.2
OperationalError
no such table: countdowns_countdown
C:\Users\0\Envs\pybay\lib\site-packages\django\db\backends\sqlite3\base.py in execute, line 323
C:\Users\0\Envs\pybay\Scripts\python.exe
3.6.4
['C:\\Users\\0\\Desktop\\pybay',  'C:\\Users\\0\\Envs\\pybay\\Scripts\\python36.zip',  'C:\\Users\\0\\Envs\\pybay\\DLLs',  'C:\\Users\\0\\Envs\\pybay\\lib',  'C:\\Users\\0\\Envs\\pybay\\Scripts',  'c:\\users\\0\\anaconda3\\Lib',  'c:\\users\\0\\anaconda3\\DLLs',  'C:\\Users\\0\\Envs\\pybay',  'C:\\Users\\0\\Envs\\pybay\\lib\\site-packages']
Wed, 21 Feb 2018 22:48:45 -0800

and this one when I on the sponsor page. 

Request Method: | GET
-- | --
http://localhost:8000/sponsors-prospectus/
1.9.2
OperationalError
no such table: menu_menuitem
C:\Users\0\Envs\pybay\lib\site-packages\django\db\backends\sqlite3\base.py in execute, line 323
C:\Users\0\Envs\pybay\Scripts\python.exe
3.6.4
['C:\\Users\\0\\Desktop\\pybay',  'C:\\Users\\0\\Envs\\pybay\\Scripts\\python36.zip',  'C:\\Users\\0\\Envs\\pybay\\DLLs',  'C:\\Users\\0\\Envs\\pybay\\lib',  'C:\\Users\\0\\Envs\\pybay\\Scripts',  'c:\\users\\0\\anaconda3\\Lib',  'c:\\users\\0\\anaconda3\\DLLs',  'C:\\Users\\0\\Envs\\pybay',  'C:\\Users\\0\\Envs\\pybay\\lib\\site-packages']
Wed, 21 Feb 2018 23:06:55 -0800

**Comment by simeonf** [comment]
If there are db tables missing thats not the requirements.txt. Run `manage.py migrate` to create any missing tables...
