### ISSUE TITLE
Migrate landing page email capture from Mailchimp to Tito

### ISSUE THREAD

**Issue by nickdirienzo** [pybay/pybay_old#222]
We'd like to use Tito for all comms related to the conference as we're selling tickets on that platform and we use it for all of the SF Python meetups. Tito doesn't have an embedded HTML email capture form like Mailchimp, but their support provided a solution that seems pretty straightforward: 

> You could hook this up with a little bit of JavaScript though, feel free to copy the implemenation at the bottom of this page here... http://2015.ull.ie 
> 
> The JavaScript for that register interest form is here...
> 
> view-source:http://2015.ull.ie/javascripts/site/register_interest.js
> 
> ...but you only need a small portion of that so hopefully it doesn't take too long to set it up e.g.
> 
> $('.register-interest-form').submit(function(){
>     name  = $('#register-name').val()
>     email = $('#register-email').val()
>     if($.trim(name) != '' && $.trim(email) != '')
>     {
>       url = ["https://ti.to/ull/2015/interested_users/subscribe.json?&interested_user[email]=", email , "&interested_user[name]=", name, "&callback=?"].join('')
>       $.getJSON(url, null, function(data){})

@lpatmo or @BethanyG would one of you be able to pick this up? Thank you! ❤️

**Comment by lpatmo** [comment]
Eek. I'm not a fan of their JS hack, but I suppose it'll work. @arturolei: any interest?

**Comment by arturolei** [comment]
Yes, I'll take a look at it later this week if that works.
