### ISSUE TITLE
Investigate and add Phone field to admin

### ISSUE THREAD

**Issue by PirosB3** [pybay/pybay_old#229]
Thanks to @lpatmo we have a phone field. Unfortunately, it looks like phone field is not being reported correctly.

# What I will do:
- Make sure we do have phone numbers recorded
- Add those fields to Admin

**Comment by BethanyG** [comment]
See https://github.com/pybay/pybay/pull/227/commits/8f270cd79463a2507a9a03ea49229464a7a0e8d6
For the recording of phone numbers.

Will investigate the second portion this afternoon, and make a fix to add to the PR if I am able.

**Comment by BethanyG** [comment]
Pull #227  ready for review, and it should contain fixes for both of these items.

**Comment by BethanyG** [comment]
Fixed and pushed live.
