### ISSUE TITLE
Show tweets from PyBay 2017 on frontpage

### ISSUE THREAD

**Issue by epsy** [pybay/pybay_old#231]
We currently show tweets from 2016

**Comment by BethanyG** [comment]
This is on my list - but thank you very much for logging an issue for tracking!

**Comment by BethanyG** [comment]
Before I go down this rabbit hole:  is **/pybay/pybay/templates/frontend/index.html** _really_ where I change these? I want to make sure I am not changing the wrong thing....

**Comment by BethanyG** [comment]
See https://github.com/pybay/pybay/pull/235.
