### ISSUE TITLE
Make template variables generate easy to style html code. This issue primarily tackles the need of a better styling in the CFP and requires intermediate/advance django knowledge

### ISSUE THREAD

**Issue by mzdaniel** [pybay/pybay_old#4]
Currently, http://www.pyconsf.com/cfp doesn't look particularly pretty and the fonts are cut in half in some  firefox platforms.  The previous iteration looked way much better. Can we customize the html code the template fields generate for easy styling?

After tackling this issue, we envision the following can be easily done with some simple CSS customization  <img width="1440" alt="screen_shot_2017-04-23_at_2 31 17_pm" src="https://cloud.githubusercontent.com/assets/68684/25419170/dbb110c2-2a05-11e7-8a52-f61fc7237db4.png">

**Comment by PirosB3** [comment]
yes, cfp is still outdated. @onur must push the new code. I suggest @onur does https://github.com/pybay/pybay/issues/5 together with this ticket

**Comment by mzdaniel** [comment]
Here is how we envision the end result will look after tackling this issue and gh-5 <img width="1440" alt="screen_shot_2017-04-23_at_2 31 17_pm" src="https://cloud.githubusercontent.com/assets/68684/25419170/dbb110c2-2a05-11e7-8a52-f61fc7237db4.png">

**Comment by mzdaniel** [comment]
Thanks to @OnurOzayyy and his wonderful implementation using django-crispy-forms, this issue was solved in a much straightforward way and can now be brought to a rest.
