### ISSUE TITLE
Have a consistent base template to inherit from

### ISSUE THREAD

**Issue by PirosB3** [pybay/pybay_old#5]
@onur I looked at your changes and I found the following inconsistency:
- `frontend/index.html` inherits from `frontend/base.html`
- `new/cfp.html` inherits from `new/base.html`.

So it looks like there are 2 base templates: `new/cfp.html` and `frontend/cfp.html`. We should keep only one of these (probably `frontend`) and delete `new`.

 - move `new/cfp.html` to `frontend/cfp.html`
 - make  `frontend/cfp.html` inherit from `frontend/base.html`
 - delete `new` directory (assuming no-one uses it any more)

**Comment by onur** [comment]
Hey, I think you meant to ping @OnurOzayyy.

**Comment by mzdaniel** [comment]
Sorry @onur. You are right. That was an oversight.

**Comment by mzdaniel** [comment]
@PirosB3: 

 - move `new/cfp.html` to `frontend/cfp.html`: Workout  in 772d935
 - make  `frontend/cfp.html` inherit from `frontend/base.html`  Done in 772d935
 - delete `new` directory (assuming no-one uses it any more)  Done in d42f0c4c

As the issues raised have been addressed, merge and in staging, I am closing this issue.
